# Generated by Django 4.0.1 on 2022-01-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('course_number', models.IntegerField(default='', max_length=5)),
                ('instructor_name', models.CharField(default='', max_length=60)),
                ('duration', models.DurationField(blank=True, default='', max_length=5, null=True)),
            ],
        ),
    ]
